name: ticketing_apps
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.9.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/nav/
    - assets/icons/payment/
    - assets/icons/settings/
flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true

